### ISSUE TITLE
项目整体设计思路

### ISSUE THREAD

**Issue by UlricQin** [cprobe/cprobe#1]
## 背景

背景信息见这篇文章：《[招贤令：一起来搞一个新的开源项目](https://mp.weixin.qq.com/s/T8B3XnXd30vT7OvsFTnaFw)》

## 整体逻辑

相当于是 Prometheus 的 Service  Discovery 部分（简称 SD） + Scrape 部分 + 各类 Exporter + Remote Write。即：通过 SD 找到要监控的目标，通过 Exporter 的逻辑来抓取指标，通过 Remote Write 发送数据到时序库。没错，这是一个缝合怪。

## 希望达成的效果

- 使用一个进程，即可监控各类目标，比如 MySQL、Redis、ElasticSearch、网络设备等。`/metrics` 暴露的数据暂不提供抓取能力，因为 Prometheus agent mode 或者 vmagent 已经可以很好的解决这个问题
- 具备方便的服务发现机制，比如 HTTP SD 来跟 CMDB 等打通，Network SD 来发现网络设备，File SD 来读取本机配置文件。以 MySQL 监控举例，原本 SD 机制发现的是 mysqld_exporter 的 `/metrics` 地址，现在直接发现 MySQL 实例的地址，直接连到这些实例上采集数据
- 各类 Exporter 只有一个规范，就是暴露 `/metrics` 接口数据，至于如何管理配置，Exporter 和目标实例之间是一对一关系还是一对多关系，都没有规范，导致不同的 Exporter 设计各异，没有一致性的体验。这个项目来解决这些一致性的体验和规范问题
- 尽量复用 Prometheus 的 scrape 配置，降低学习成本，并对 scrape 配置做扩展，比如监控网络设备要配置各类 OID，监控 Postgres 要配置一些 SQL 语句，这类配置姑且称为采集规则：scrape_rules，scrape_configs 中要引用这些 scrape_rules，并对这些 rules 进行切文件管理

## 举例

以 MySQL 监控举例，大概需要这么配置 scrape_configs：

```yaml
scrape_configs:
- job_name: mysql-prod
  scrape_rules:
  - /etc/prometheus/mysql.rules/common.toml
  - /etc/prometheus/mysql.rules/schema_size.toml
  - /etc/prometheus/mysql.rules/biz.toml
  static_configs:
  - targets:
    - 10.1.2.3:3306
    - 10.1.2.5:3306
    labels:
      group: "mysql_from_static"
```

MySQL 有一些通用的采集规则，放到 common.toml 中，比如采集 global status、global variables，有一些不太通用的采集规则则放在其他规则文件中，比如采集 schema 大小的配置放到 schema_size.toml，业务自定义的监控 SQL 放到 biz.toml 中。之所以用 toml 举例，是因为多个 toml rule 直接 merge 成一个大配置即可，如果是 json 或者 yaml 就不太好 merge 处理了。

各类 SD 发现的 target 列表，格式如下（使用 json 举例）：

```json
[
    {
        "targets": ["10.1.2.3:3306"],
        "labels": {
            "project": "foo",
            "region": "beijing"
        }
    },
    {
        "targets": ["10.1.2.4:3306"],
        "labels": {
            "project": "bar",
            "region": "beijing"
        }
    }
]
```

labels 部分是个 map，我也有在考虑是否引入一个 path 的概念来表示树路径，很多 CMDB 在维护 target 的时候，都是挂到树形结构下。一个 target 可能会挂在多个节点下，导致没法使用 map 来描述这个关系。引入 path 之后，结构举例：

```json
[
    {
        "targets": ["10.1.2.3:3306"],
        "labels": {
            "project": "foo",
            "region": "beijing"
        },
        "paths": [
            "dba.cloud",
            "dba.shop"
        ]
    },
    {
        "targets": ["10.1.2.4:3306"],
        "labels": {
            "project": "bar",
            "region": "beijing"
        },
        "paths": [
            "dba.cloud"
        ]
    }
]
```

之后在 scrape_configs 中可以基于 paths 信息做过滤，不过这个设计尚未想清楚。

对于 Prometheus 而言，只需要发现 HTTP 抓取地址即可，但现在我们想直接抓目标 target，比如要抓网络设备，这个时候就需要额外的 SD 机制，比如 snmp_sd_configs，举例：

```yaml
scrape_configs:  
  snmp_sd_configs:
  - refresh_interval: 1m
    cidr:
    - "10.1.2.0/24"
    - "10.1.3.0/24"
    range:
    - "10.2.3.2-254"
    - "10.2.3.3-254"
    port: 3306
    community: public
    version: 2
```

## 其他改造和重难点

关于认证，原本 Prometheus 只需要处理 HTTP 相关的认证，现在要直连监控目标，可能要处理不同的认证方式，比如网络设备有 SNMP 专属认证机制，MySQL 则走 TCP，不同的 scrape job 就需要不同的认证机制。

Prometheus 有多种不同的 SD 机制，现在要直连监控目标，SD 相关的代码需要想办法复用，如果每类监控目标都要拷贝一坨 SD 代码就非常麻烦了。后面再具体考虑。

任何问题或建议，欢迎留言.
